# lightning.pytorch==2.2.1
seed_everything: true

data:
  class_path: dataset_utils.LightningDataModules.Era2CerraDataModule
  init_args:
    data_path:  data/
    downscaling_factor: 4
    num_workers: 1
    batch_size:  8
    crop_size: 256
    channel_names: [ 'u10', 'v10', 't2m', 'sp', 'msl', 't850', 'u1000', 'v1000', 'z1000', 'u850', 'v850', 'z850', 'u500', 'v500', 'z500', 't500', 'z50', 'r500', 'r850', 'tcwv']
    use_separate_dataset: true
    constant_channels: true
    train_years: [2020, 2020]
    val_years: [2020, 2020]
    test_years: [2020, 2020]
    return_offset: true
    return_era_original: true

model:
  ##LightweightSwinFIR
  class_path: models.swin_fir.swin_fir.SwinFIR_sidechannel
  init_args:   
    learning_rate: 1.5e-4
    img_size: 64
    window_size: 8
    img_range: 1.
    depths: [5,5,5,5,5] # [6,5,5,6]
    embed_dim: 220
    num_heads: [6,6,6,6,6]
    mlp_ratio: 2
    upsampler: "pixelshuffledirect"
    in_chans: 20
    resi_connection: 'HSFB'
    num_sidechannels: 2
    embed_dim_sidechannels: 20
    loss_beta: 0.6
    ape: false
    

trainer:

  logger:
    class_path: WandbLogger
    init_args:
      name: "test-example"
      project: "masterthesis"
      entity: "shiemn"
      group: "era2cerra"
      job_type: "train"
      tags: ['swinFIR', '4x', 'u10/v10']

  accelerator: 'cpu' #Change to 'auto' for GPU
  fast_dev_run: false
  callbacks:
    - class_path: utils.isd_callback.ISDValidationCallback
      init_args:
        isd_data_path: "data/ISD"
        start_date: "20200601" 
        end_date: "20200701"
    - class_path: utils.dwd_callback.DWDValidationCallback
      init_args:
        cdc_data_path: "data/CDC"
        start_date: "20200101"
        end_date: "20210701"
    
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: "00:23:00:00"
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: 5
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null

 
default_early_stopping:
  monitor: val_loss
  min_delta: 0.0
  patience: 3
  verbose: true
  mode: min
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
  log_rank_zero_only: false

default_checkpoint:
  dirpath: output/models
  filename: example
  monitor: val_loss
  verbose: true
  save_last: true
  save_top_k: 1
  save_weights_only: false
  mode: min
  auto_insert_metric_name: true
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
  enable_version_counter: true



